#!/usr/bin/env python3
"""Precompute planetary positions into static JSON for the game to read.

Build-time only. The game never runs this — it reads the JSON this writes.

Why precompute at all: the puzzles need real geometry (where Venus actually is
at twilight, where Mars actually is when it appears to run backwards), but the
answers are deterministic. Computing them once and committing the result keeps
the game a pile of static files with no Python process behind it.

Usage:
    .venv/bin/python data/scripts/orbital-positions.py
    .venv/bin/python data/scripts/orbital-positions.py --start 2026-01-01 --days 730
"""

from __future__ import annotations

import argparse
import json
from datetime import date, timedelta
from pathlib import Path

from skyfield.api import load, load_file

REPO_ROOT = Path(__file__).resolve().parents[2]
EPHEMERIS_DIR = REPO_ROOT / "data" / "ephemeris"
OUTPUT_PATH = REPO_ROOT / "data" / "generated" / "orbital-positions.json"

# de440s covers 1849-2150 in ~32MB. de440 is ~114MB and buys us centuries this
# game will never show a child. Smaller kernel = faster first run on a laptop.
EPHEMERIS_NAME = "de440s.bsp"

# Bodies the game actually teaches. Kept to the solar system on purpose: the
# brief puts anything interstellar out of scope for v1.
BODIES: dict[str, str] = {
    "mercury": "mercury barycenter",
    "venus": "venus barycenter",
    "earth": "earth",
    "mars": "mars barycenter",
    "jupiter": "jupiter barycenter",
    "saturn": "saturn barycenter",
    "moon": "moon",
}


def _load_ephemeris():
    """Load the DE kernel, downloading it once into data/ephemeris/."""
    EPHEMERIS_DIR.mkdir(parents=True, exist_ok=True)
    local = EPHEMERIS_DIR / EPHEMERIS_NAME
    if local.exists():
        return load_file(str(local))
    loader = load.__class__(str(EPHEMERIS_DIR))
    return loader(EPHEMERIS_NAME)


def compute(start: date, days: int, step_days: int) -> dict[str, object]:
    """Geocentric apparent positions, sampled every `step_days`.

    Returns RA/Dec (where a body appears on the sky) plus distance in AU. RA/Dec
    is what a sky-watching puzzle needs; the heliocentric ecliptic longitude is
    what an orbit-path puzzle needs, so both are emitted.
    """
    ephemeris = _load_ephemeris()
    timescale = load.timescale()
    earth = ephemeris["earth"]
    sun = ephemeris["sun"]

    samples = [start + timedelta(days=offset) for offset in range(0, days, step_days)]
    times = timescale.utc(
        [d.year for d in samples],
        [d.month for d in samples],
        [d.day for d in samples],
    )

    out: dict[str, object] = {}
    for key, target in BODIES.items():
        body = ephemeris[target]

        ra, dec, distance = earth.at(times).observe(body).apparent().radec()
        helio = sun.at(times).observe(body).ecliptic_latlon()

        out[key] = {
            "dates": [d.isoformat() for d in samples],
            # Right ascension in hours, declination in degrees: where it appears.
            "raHours": [round(v, 6) for v in ra.hours.tolist()],
            "decDegrees": [round(v, 6) for v in dec.degrees.tolist()],
            "distanceAu": [round(v, 8) for v in distance.au.tolist()],
            # Heliocentric ecliptic longitude in degrees: where it is in its
            # orbit. This is what the Mars retrograde walk-the-orbits puzzle
            # needs to draw both paths side by side.
            "helioLonDegrees": [round(v, 6) for v in helio[1].degrees.tolist()],
        }
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--start", default=date.today().isoformat(), help="ISO start date"
    )
    parser.add_argument("--days", type=int, default=365, help="span in days")
    parser.add_argument("--step", type=int, default=1, help="sample every N days")
    args = parser.parse_args()

    start = date.fromisoformat(args.start)
    bodies = compute(start, args.days, args.step)

    payload = {
        "_readme": (
            "Generated by data/scripts/orbital-positions.py. Do not edit by hand. "
            "Geocentric apparent RA/Dec and heliocentric ecliptic longitude, "
            "sampled daily. Regenerate rather than patch."
        ),
        "source": f"JPL {EPHEMERIS_NAME} via Skyfield",
        "generated": date.today().isoformat(),
        "start": start.isoformat(),
        "days": args.days,
        "stepDays": args.step,
        "bodies": bodies,
    }

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    size_kb = OUTPUT_PATH.stat().st_size / 1024
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
